# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f37f7c22dfd370fd0d53546b6f31953db60c0f4c76bbc661fe092e0154569e439794059743584b25275c5035142ffc5f93867a285d3a2c786d5bcfcdfd53ec4

test:
  secret_key_base: 26369fd0218e820adf5fb021d7f8c293e39eb33182292fcbad9ddfd7c1de54397cca412fc03777d3333018a4da943b3a507cf339e3124cc1ab0acdef7bfa94ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 26369fd0218e820adf5fb021d7f8c293e39eb33182292fcbad9ddfd7c1de54397cca412fc03777d3333018a4da943b3a507cf339e3124cc1ab0acdef7bfa94ae
